/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard.conversations'
import { Route as DashboardDemandesRouteImport } from './routes/dashboard.demandes'
import { Route as DashboardProspectsRouteImport } from './routes/dashboard.prospects'
import { Route as ExpertisesSlugRouteImport } from './routes/expertises.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDemandesRoute = DashboardDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProspectsRoute = DashboardProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => DashboardRoute,
} as any)
const ExpertisesSlugRoute = ExpertisesSlugRouteImport.update({
  id: '/expertises/$slug',
  path: '/expertises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/demandes': typeof DashboardDemandesRoute
  '/dashboard/prospects': typeof DashboardProspectsRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/demandes': typeof DashboardDemandesRoute
  '/dashboard/prospects': typeof DashboardProspectsRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/devis': typeof DevisRoute
  '/realisations': typeof RealisationsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/demandes': typeof DashboardDemandesRoute
  '/dashboard/prospects': typeof DashboardProspectsRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/devis'
    | '/realisations'
    | '/dashboard/conversations'
    | '/dashboard/demandes'
    | '/dashboard/prospects'
    | '/expertises/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/devis'
    | '/realisations'
    | '/dashboard/conversations'
    | '/dashboard/demandes'
    | '/dashboard/prospects'
    | '/expertises/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/devis'
    | '/realisations'
    | '/dashboard/conversations'
    | '/dashboard/demandes'
    | '/dashboard/prospects'
    | '/expertises/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevisRoute: typeof DevisRoute
  RealisationsRoute: typeof RealisationsRoute
  ExpertisesSlugRoute: typeof ExpertisesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/demandes': {
      id: '/dashboard/demandes'
      path: '/demandes'
      fullPath: '/dashboard/demandes'
      preLoaderRoute: typeof DashboardDemandesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prospects': {
      id: '/dashboard/prospects'
      path: '/prospects'
      fullPath: '/dashboard/prospects'
      preLoaderRoute: typeof DashboardProspectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/expertises/$slug': {
      id: '/expertises/$slug'
      path: '/expertises/$slug'
      fullPath: '/expertises/$slug'
      preLoaderRoute: typeof ExpertisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardDemandesRoute: typeof DashboardDemandesRoute
  DashboardProspectsRoute: typeof DashboardProspectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardDemandesRoute: DashboardDemandesRoute,
  DashboardProspectsRoute: DashboardProspectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevisRoute: DevisRoute,
  RealisationsRoute: RealisationsRoute,
  ExpertisesSlugRoute: ExpertisesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
